# Generated by Django 5.1.3 on 2025-05-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='categoria',
            field=models.CharField(choices=[('A1', 'Iniciante'), ('A2', 'Básico'), ('B1', 'Intermediário'), ('B2', 'Intermediário avançado'), ('C1', 'Avançado'), ('C2', 'Proficiente')], default='A1', max_length=15),
        ),
    ]
